spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/SocialApps
    username: root
    password: 123456

# MyBatis-Plus全局配置
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.microsoft.week4.demoProj.Entity

